spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

application:
  security:
    jwt:
      secret-key: 6241366352563d337a267e5e3454373f69582478374f375c3c3a537731
      expiration: 600000 # 10 min
      refresh-token:
        expiration: 604800000 # 7 days